### ISSUE TITLE
Class: ServerConnection

### ISSUE THREAD

**Issue by exactmark** [VishalBilagi/GeoCached#14]
Acts as boundary between app and server. 

Should allow testing without active server by returning test objects when appropriate.

**Comment by VishalBilagi** [comment]
@exactmark Is this something we should be doing? We plug in all our API calls in [ServerConnection](https://github.com/VishalBilagi/GeoCached/blob/master/GeoCached/app/src/main/java/com/team4/geocached/ServerConnection.java) class (maybe more helper classes as needed)

**Comment by VishalBilagi** [comment]
Needs to parse JSON data to match User/Location/LogEntry classes
